# Generated by Django 5.2.4 on 2025-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
