# Generated by Django 5.0.2 on 2025-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="content",
            field=models.TextField(default="Placeholder content"),
        ),
    ]
