# Generated by Django 5.2.4 on 2025-07-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_fileupload_file_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('DELETE', 'Delete'), ('ACCESS', 'Access')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='fileupload',
            constraint=models.UniqueConstraint(fields=('user', 'file_hash'), name='unique_user_file_hash'),
        ),
        migrations.AddField(
            model_name='filelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
