# Generated by Django 5.2.4 on 2025-07-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_uploadedfile_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='text',
            field=models.TextField(default='Placeholder conversation'),
            preserve_default=False,
        ),
    ]
