# Generated by Django 5.2.4 on 2025-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='checksum',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
