# Generated by Django 5.2.4 on 2025-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(default='dummy', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
