# Generated by Django 5.2.4 on 2025-07-04 20:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_filechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunk',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='filechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chat_filech_search__76f3b8_gin'),
        ),
    ]
