# Generated by Django 5.2.4 on 2025-07-05 10:06

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_filechunk_chunk_index_filechunk_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filechunk',
            options={'ordering': ['chunk_index']},
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
